### ISSUE TITLE
migrate to Google Custom Search Element API 2.0

### ISSUE THREAD

**Issue by bubblebenj** [HaxeFoundation/haxe.org#271] opened 2017-09-11 19:01 UTC
I've received today a mail from google to update the search engine (because I created on the old haxe website). Here is it's content:

> Dear Custom Search Engine Administrator,
> 
> The [Custom Search Element API 1.0](https://www.google.com/appserve/mkt/p/ALM6Bvycr3wiVG3dMDL4z_T7z6q7km1rmZS-9J9c86QnSvA4MVDkvZyhyG4M6ILLO-mxb5en1-2fEFB2-YMetmzkQRnzCUZJW-tpBLKTzQGbDdq5rDubZpsuzWQ9vSoIehHzbfQHiaNQjtl-), which was deprecated in 2012 in favor of [API 2.0](https://www.google.com/appserve/mkt/p/ALM6BvwMAdYpsnRfkDIuHlVva1oi2IuKnwJuaRCusTsIGj4_va_tM3Ti9y5OijZe5MTVAvkIO5j6d-RW4Cdyobn8Oz-t4QXNenHEyBKFcOitKOLtpMZPwr0xi6sOSw), is now no longer maintained. API 1.0 will stop working on December 4, 2017.
> 
> You’re receiving this message because our records show you might currently be using the Custom Search Element API 1.0. You can confirm if you’re using this version by looking at the code on your search page for a call to google.search.CustomSearchControl.
> 
> Next Steps
> 
> To avoid an interruption in service, please update your website to use the Custom Search Element API 2.0 before December 4, 2017. The easiest way to transition is through the CSE Control Panel at [cse.google.com](https://www.google.com/appserve/mkt/p/ALM6Bvya47iA-YOFslU5nPoQSw2-giBAKNY_X29Rw_R6RaekerqNZQVnA5Lk5I4FCuOsZZpQ8bevwClj), where you can [generate](https://www.google.com/appserve/mkt/p/ALM6Bvz32KmftW9XG4JDjX8N_57-Mtn49YUPESdNXZnXccoFfyWBA12iO8x43YsXzhHlYpfEIUeNzwiFphl8-QjBrUCi8EMK5Y1ugSQd73ApCQY2HdQ-s4Jy-g4) your new Custom Search Engine code and add it to your website.
> 
> We’re always improving the Custom Search Engine and we thank you for your support. For more information about the Custom Search Element API, visit Google Developers.
> 
> Sincerely,
> The Custom Search Engine Team

**Comment by markknol** [comment] 2017-09-12 06:42
Hi, Thanks for notifying! But we already had a ticket for it.
I close it since it is a duplicate of https://github.com/HaxeFoundation/haxe.org/issues/249

**Closed by markknol** 2017-09-12 06:42 UTC

**Comment by bubblebenj** [comment] 2017-09-12 18:58
Humm, actually I've seen it but didn't know what it was about since I don't remember fees were involved.
I believe GSS (for enterprise) and GCS are two different beast, and the second one (that [we are currently using](https://github.com/HaxeFoundation/haxe.org/blob/staging/pages/search/index.html)) is not discontinued, only v1 will be.
