### ISSUE TITLE
No 404 page on wrong subdomain ?

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe.org#290] opened 2017-12-22 08:18 UTC
If I mistype `http://hapi.haxe.org/`, I get:

<img width="725" alt="screen shot 2017-12-22 at 09 15 59" src="https://user-images.githubusercontent.com/1238030/34290624-c72db352-e6f8-11e7-83c5-7c9f8ed00f86.png">

It would look better with some customized page like on other websites: 

<img width="1051" alt="screen shot 2017-12-22 at 09 17 39" src="https://user-images.githubusercontent.com/1238030/34290680-0db28f96-e6f9-11e7-979a-e0b1d3da4126.png">

**Comment by markknol** [comment] 2017-12-22 08:55
@andyli can we redirect all 404's to haxe.org?

**Comment by ibilon** [comment] 2017-12-22 08:56
Duplicate of https://github.com/HaxeFoundation/haxe.org/issues/233

**Closed by ibilon** 2017-12-22 08:56 UTC
